import Link from "next/link";
import { ArrowLeft, Download, FileText, Pencil, Plus, Trash2, Upload } from "lucide-react";
import { notFound } from "next/navigation";
import { requireUser } from "@/lib/auth";
import { getCompaniesForUser, getProjectForUser, getProjectTypes } from "@/lib/data";
import { formatDate, formatDateTime, formatQar, humanFileSize } from "@/lib/utils";
import { Modal } from "@/components/modal";
import { ProjectForm } from "@/components/project-form";
import { TaskForm } from "@/components/task-form";
import { ProgressBar, StatusBadge, TypeBadge } from "@/components/status-badge";
import { Flash } from "@/components/flash";
import { TaskStatusSelect } from "@/components/task-status-select";
import { ConfirmSubmit } from "@/components/confirm-submit";
import { createProjectNote, deleteDocument, deleteProject } from "@/app/actions";

export default async function ProjectPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ success?: string; error?: string }> }) {
  const user = await requireUser();
  const [{ id }, flash] = await Promise.all([params, searchParams]);
  const [project, companies, projectTypes] = await Promise.all([getProjectForUser(user, id), getCompaniesForUser(user), getProjectTypes()]);
  if (!project) notFound();
  const isAdmin = user.role === "ADMIN";
  return <>
    <Link href={`/projects?company=${project.companyId}`} className="button ghost" style={{ marginBottom: ".7rem" }}><ArrowLeft /> Back to company portfolio</Link>
    <Flash success={flash.success} error={flash.error} />
    <section className="detail-hero">
      <div className="detail-title"><div><div className="eyebrow">{project.companyName} · {project.companyCode}</div><h1>{project.name}</h1><p className="lede">{project.description || "No project description yet."}</p></div><div className="toolbar"><StatusBadge status={project.status} /><TypeBadge type={project.projectTypeName} />{isAdmin && <Modal title="Edit project" trigger={<button type="button" className="button secondary"><Pencil /> Edit</button>}><ProjectForm companies={companies} projectTypes={projectTypes} project={project} /></Modal>}{isAdmin && <form action={deleteProject}><input type="hidden" name="id" value={project.id} /><ConfirmSubmit confirmText={`Delete ${project.name}? Its tasks, notes, and documents will also be deleted.`}><Trash2 /> Delete</ConfirmSubmit></form>}</div></div>
      <div className="detail-meta"><div className="detail-stat"><span>Cost</span><strong>{formatQar(project.costQar)}</strong></div><div className="detail-stat"><span>Start date</span><strong>{formatDate(project.startDate)}</strong></div><div className="detail-stat"><span>Target date</span><strong>{formatDate(project.targetDate)}</strong></div><div className="detail-stat" style={{ minWidth: "12rem", flex: 1 }}><ProgressBar value={project.progress} /></div></div>
    </section>
    <div className="grid-two">
      <section className="panel"><div className="panel-head"><div><h2>Delivery tasks</h2><div className="hint">{project.tasks.filter((task) => task.status === "DONE").length} of {project.tasks.length} complete</div></div>{isAdmin && <Modal title="Add task" trigger={<button type="button" className="button"><Plus /> Add task</button>}><TaskForm projectId={project.id} /></Modal>}</div><div className="panel-body"><div className="stack">{project.tasks.length ? project.tasks.map((task) => <article className="task" key={task.id}><div className="task-top"><div><h3 className="task-title">{task.title}</h3><div className="file-meta">Due {formatDateTime(task.dueAt)}</div></div><div className="toolbar">{isAdmin ? <TaskStatusSelect id={task.id} projectId={project.id} title={task.title} value={task.status} /> : <StatusBadge status={task.status} />}{isAdmin && <Modal title="Edit task" trigger={<button type="button" className="icon-button" aria-label={`Edit ${task.title}`}><Pencil size={16} /></button>}><TaskForm projectId={project.id} task={task} /></Modal>}</div></div>{task.description && <p>{task.description}</p>}<div className="task-notes"><strong>Notes</strong><p>{task.notes || "No notes yet."}</p></div></article>) : <div className="empty">No tasks yet. Progress remains at 0% until tasks are added.</div>}</div></div></section>
      <div className="stack"><section className="panel"><div className="panel-head"><div><h2>Project notes</h2><div className="hint">A dated record of project updates</div></div>{isAdmin && <Modal title="Add project note" trigger={<button type="button" className="button secondary"><Plus /> Add note</button>}><form action={createProjectNote}><input type="hidden" name="projectId" value={project.id} /><div className="field"><label htmlFor="project-note">Note</label><textarea className="input" id="project-note" name="content" required maxLength={10000} placeholder="Add an update, decision, or important context…" /></div><div className="form-actions"><button className="button" type="submit">Add note</button></div></form></Modal>}</div><div className="panel-body"><div className="stack">{project.generalNotes ? <article className="note-entry pinned"><div className="file-meta">General note</div><div className="notes">{project.generalNotes}</div></article> : null}{project.notes.map((note) => <article className="note-entry" key={note.id}><div className="file-meta">{note.authorName} · {formatDateTime(note.createdAt)}</div><div className="notes">{note.content}</div></article>)}{!project.generalNotes && !project.notes.length ? <div className="empty">No project notes yet.</div> : null}</div></div></section>
      <section className="panel"><div className="panel-head"><div><h2>Documents</h2><div className="hint">Up to 4 MB per file</div></div>{isAdmin && <Modal title="Upload document" trigger={<button type="button" className="button secondary"><Upload /> Upload</button>}><form action={`/api/projects/${project.id}/documents`} method="post" encType="multipart/form-data"><div className="stack"><div className="field"><label htmlFor="document-name">Document name</label><input className="input" id="document-name" name="displayName" required maxLength={255} placeholder="e.g. Approved project brief" /></div><div className="field"><label htmlFor="document">Choose a document</label><input className="input" id="document" name="document" type="file" accept=".pdf,.doc,.docx,.xls,.xlsx,.csv,.txt,.png,.jpg,.jpeg" required /></div></div><p className="hint">PDF, Office, text, CSV, PNG, and JPEG files are accepted. The original extension is preserved when needed.</p><div className="form-actions"><button className="button" type="submit">Upload document</button></div></form></Modal>}</div><div className="panel-body">{project.documents.length ? project.documents.map((document) => <div className="document-row" key={document.id}><div><div className="file-name"><FileText size={15} style={{ display: "inline", marginRight: ".4rem" }} />{document.name}</div><div className="file-meta">{humanFileSize(Number(document.sizeBytes))} · {document.uploaderName} · {formatDateTime(document.createdAt)}</div></div><Link className="button ghost" href={`/api/documents/${document.id}`}><Download /> Download</Link>{isAdmin && <form action={deleteDocument}><input type="hidden" name="id" value={document.id} /><input type="hidden" name="projectId" value={project.id} /><button className="button danger" type="submit">Remove</button></form>}</div>) : <div className="empty"><FileText /><p>No documents uploaded.</p></div>}</div></section></div>
    </div>
  </>;
}
